### PR TITLE
Create .travis.yml

### PR DESCRIPTION
**Pull request by den-run-ai**
@vmuriart @cowboygneox please review

### CODE REVIEW

**Comment by den-run-ai** [comment]
it is also possible to get the builds from docker cloud:

image

**Comment by vmuriart** [comment]
have you tried configuring the autobuild? seems like a better solution.
I'll defer to @cowboygneox on changing the `mono` version on docker. not sure if he a specific reason to chose that one.

**Comment by cowboygneox** [comment]
@vmuriart I chose the version because it was the latest at time of writing.

**Comment by cowboygneox** [comment]
LGTM. TravisCI has come a long way.

**Comment by den-run-ai** [comment]
@vmuriart are you ok with merging this? I'm testing docker hub autobuilds and would like to use them for builds from master and keep travis builds for versioned releases.

**Pull request merged**
